POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{}

### 
PUT http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIwMWMyZTZhOC03ZjRmLTQzZTctOTU4Zi0wODhiYzBkZDUxM2EiLCJpYXQiOjE3NjQ4NzUwODksImV4cCI6MTc2NDg3ODY4OX0.8RFF74S8xdxs8kT-ttXvby4PtlXVVufLtx8vqdh6PFA

{
    "email": "new@mail.ru",
    "password": "12121212"
}

###
POST http://localhost:8080/api/revoke
Content-Type: application/json
Authorization: Bearer eeda200b100d5e230a00edf45837f00c961b425a9eafddb4970a86761fe378b7


###
POST http://localhost:8080/api/refresh
Content-Type: application/json
Authorization: Bearer aeedf47ec3673a17be8495c062aa4165829ab3e27c81fd0293b469ad947abb98

###

GET http://localhost:8080/api/chirps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIwMWMyZTZhOC03ZjRmLTQzZTctOTU4Zi0wODhiYzBkZDUxM2EiLCJpYXQiOjE3NjQ5NjIwNjMsImV4cCI6MTc2NDk2NTY2M30.KkZHabFaNbD0Zectxi5J4ID3XauI3kp-J_FKvW3V71Q

### Create a user
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "pawlik_by@mail.ru",
    "password": "12345678"
}

### Login 
POST http://localhost:8080/api/login
Content-Type: application/json

{
    //"password": "87654321",
    "password": "12345678",
    //"email": "pashalevy@gmail.com"
    "email": "pawlik_by@mail.ru"
    //"email": "new@mail.ru"
}

### Create chirp
POST http://localhost:8080/api/chirps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiI5MmNmMWJkZS0wOTI0LTQ4MjgtODQ1YS0wMGFhN2ZjMzI0YjciLCJpYXQiOjE3NjUzMDQ5NTAsImV4cCI6MTc2NTMwODU1MH0.Zit_T8jvSwhmXUd4zhFXqpKGPv9-UhntaG2qTiFt6sQ

{
    "body": "Hello world! =P",
    "userId": "92cf1bde-0924-4828-845a-00aa7fc324b7"
}

###
GET http://localhost:8080/api/chirps/32736a51-1897-4490-867b-13295ffe54b5

### Reset all users
POST http://localhost:8080/admin/reset



### Delete chirp not authenticated
DELETE http://localhost:8080/api/chirps/1234

### Delete chirp with invalid token
DELETE http://localhost:8080/api/chirps/1234
Authorization: Bearer invalidtoken

### Delete chirp when not author
DELETE http://localhost:8080/api/chirps/a89cf178-9427-49d7-ae74-5da46c3c5493
Authorization: Bearer 9098

### Delete chirp when author (should return 204)
DELETE http://localhost:8080/api/chirps/a89cf178-9427-49d7-ae74-5da46c3c5493
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIwMWMyZTZhOC03ZjRmLTQzZTctOTU4Zi0wODhiYzBkZDUxM2EiLCJpYXQiOjE3NjQ5NjIwNjMsImV4cCI6MTc2NDk2NTY2M30.KkZHabFaNbD0Zectxi5J4ID3XauI3kp-J_FKvW3V71Q

### Webhook test
### Event is NOT user.upgraded → Expect 204
POST http://localhost:8080/api/polka/webhooks
Content-Type: application/json

{
  "event": "invoice.paid",
  "data": {
    "userId": "01c2e6a8-7f4f-43e7-958f-088bc0dd513a"
  }
}

### Upgrade existing user → Expect 204

POST http://localhost:8080/api/polka/webhooks
Content-Type: application/json

{
  "event": "user.upgraded",
  "data": {
    "userId": "01c2e6a8-7f4f-43e7-958f-088bc0dd513a"
  }
}

### User does not exist → Expect 404
POST http://localhost:8080/api/polka/webhooks
Content-Type: application/json

{
  "event": "user.upgraded",
  "data": {
    "userId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
  }
}

### Missing data.userId → Expect 400

POST http://localhost:8080/api/polka/webhooks
Content-Type: application/json

{
  "event": "user.upgraded",
  "data": {}
}

### Testing Polka with API Key
### Valid upgrade request (should mark user as Chirpy Red)
POST http://localhost:8080/api/polka/webhooks
Content-Type: application/json
Authorization: ApiKey f271c81ff7084ee5b99a5091b42d486e

{
  "event": "user.upgraded",
  "data": {
    "userId": "01c2e6a8-7f4f-43e7-958f-088bc0dd513a"
  }
}

### Testing GET for return chirps by author or all
GET http://localhost:8080/api/chirps?authorId=92cf1bde-0924-4828-845a-00aa7fc324b7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiI5MmNmMWJkZS0wOTI0LTQ4MjgtODQ1YS0wMGFhN2ZjMzI0YjciLCJpYXQiOjE3NjUzMDQ4MzYsImV4cCI6MTc2NTMwODQzNn0.xa9VXTy_R0rmvmOFdCxT1x70u2t9lJT8ru05Hv2aaQE

